Repository dnd-side-project/dnd-11th-4-iOS, pull requests merged in 2024-08, with the labels that each got.

#8 [FEAT] #5 - 공통 컴포넌트 구현
  dnd-11th-4-iOS/dnd-11th-4-iOS.xcodeproj/project.pbxproj
  dnd-11th-4-iOS/dnd-11th-4-iOS/Application/SceneDelegate.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/UIComponent/MDButton.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/UIComponent/MDLabel.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/UIComponent/MDPopUpView.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/UIComponent/MDToast.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/UIComponent/MDToastView.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/Home/HomeMap/HomeMap_강원도.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/Home/HomeMap/HomeMap_경기도.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/Home/HomeMap/HomeMap_경상남도.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/Home/HomeMap/HomeMap_경상북도.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/Home/HomeMap/HomeMap_광주.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/Home/HomeMap/HomeMap_대구.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/Home/HomeMap/HomeMap_대전.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/Home/HomeMap/HomeMap_부산.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/Home/HomeMap/HomeMap_서울.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/Home/HomeMap/HomeMap_세종시.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/Home/HomeMap/HomeMap_울산.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/Home/HomeMap/HomeMap_인천.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/Home/HomeMap/HomeMap_전라남도.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/Home/HomeMap/HomeMap_전라북도.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/Home/HomeMap/HomeMap_제주도.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/Home/HomeMap/HomeMap_충청남도.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/Home/HomeMap/HomeMap_충청북도.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/Home/ViewController/HomeViewController.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/MyPage/MyPageViewController.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/Onboarding/OnboardingMap/OnboardingMap_강원도.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/Onboarding/OnboardingMap/OnboardingMap_경기도.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/Onboarding/OnboardingMap/OnboardingMap_경상남도.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/Onboarding/OnboardingMap/OnboardingMap_경상북도.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/Onboarding/OnboardingMap/OnboardingMap_광주.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/Onboarding/OnboardingMap/OnboardingMap_대구.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/Onboarding/OnboardingMap/OnboardingMap_대전.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/Onboarding/OnboardingMap/OnboardingMap_부산.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/Onboarding/OnboardingMap/OnboardingMap_서울.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/Onboarding/OnboardingMap/OnboardingMap_울산.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/Onboarding/OnboardingMap/OnboardingMap_인천.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/Onboarding/OnboardingMap/OnboardingMap_전라남도.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/Onboarding/OnboardingMap/OnboardingMap_전라북도.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/Onboarding/OnboardingMap/OnboardingMap_제주도.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/Onboarding/OnboardingMap/OnboardingMap_충청남도.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/Onboarding/OnboardingMap/OnboardingMap_충청북도.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/PopUp/PopupViewController.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/RecordList/RecordListViewController.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/TabBar/TabBarViewController.swift
Labels: 찬미 🐹, FEAT

#12 [FEAT] #11 - RecordListView 구현
  dnd-11th-4-iOS/dnd-11th-4-iOS.xcodeproj/project.pbxproj
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/Constant/Constant.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/DesignSystem/Assets.xcassets/IconEdit.imageset/Contents.json
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/DesignSystem/Assets.xcassets/IconEdit.imageset/IconEdit.png
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/DesignSystem/Assets.xcassets/IconEdit.imageset/IconEdit@2x.png
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/DesignSystem/Assets.xcassets/IconEdit.imageset/IconEdit@3x.png
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/DesignSystem/Assets.xcassets/ImageEmpty.imageset/Contents.json
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/DesignSystem/Assets.xcassets/ImageEmpty.imageset/Frame 315.png
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/DesignSystem/Assets.xcassets/ImageEmpty.imageset/Frame 315@2x.png
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/DesignSystem/Assets.xcassets/ImageEmpty.imageset/Frame 315@3x.png
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/Extension/UIImage+.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/UIComponent/MDButton.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/UIComponent/MDNavigationBar.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/UIComponent/MDPopUpView.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/UIComponents/NavigationBar.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/PopUp/ListDeleteViewController.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/PopUp/PopupViewController.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/RecordList/EmptyRecordView.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/RecordList/MenuAlertView.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/RecordList/RecordListCell.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/RecordList/RecordListHeaderView.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/RecordList/RecordListReactor.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presetation/RecordList/RecordListViewController.swift
Labels: 우연 🐶, FEAT

#16 [Feat] #13 - Onboarding 및 Splash View 구현
  dnd-11th-4-iOS/dnd-11th-4-iOS.xcodeproj/project.pbxproj
  dnd-11th-4-iOS/dnd-11th-4-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  dnd-11th-4-iOS/dnd-11th-4-iOS/Application/SceneDelegate.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/Constant/Constant.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/DesignSystem/Assets.xcassets/ImageStart.imageset/Contents.json
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/DesignSystem/Assets.xcassets/ImageStart.imageset/untitled454545 copy 1.png
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/DesignSystem/Assets.xcassets/ImageStart.imageset/untitled454545 copy 1@2x.png
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/DesignSystem/Assets.xcassets/ImageStart.imageset/untitled454545 copy 1@3x.png
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/DesignSystem/Assets.xcassets/logoBlack.imageset/Contents.json
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/DesignSystem/Assets.xcassets/logoBlack.imageset/logo.png
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/DesignSystem/Assets.xcassets/logoBlack.imageset/logo@2x.png
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/DesignSystem/Assets.xcassets/logoBlack.imageset/logo@3x.png
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/DesignSystem/Assets.xcassets/logoWhite.imageset/Contents.json
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/DesignSystem/Assets.xcassets/logoWhite.imageset/mapddang.png
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/DesignSystem/Assets.xcassets/logoWhite.imageset/mapddang@2x.png
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/DesignSystem/Assets.xcassets/logoWhite.imageset/mapddang@3x.png
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/DesignSystem/Font/Font.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/Onboarding/Model/ColorType.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/Onboarding/OnboardingMap/OnboardingMap_강원도.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/Onboarding/OnboardingMap/OnboardingMap_경기도.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/Onboarding/OnboardingMap/OnboardingMap_경상남도.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/Onboarding/OnboardingMap/OnboardingMap_경상북도.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/Onboarding/OnboardingMap/OnboardingMap_광주.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/Onboarding/OnboardingMap/OnboardingMap_대구.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/Onboarding/OnboardingMap/OnboardingMap_대전.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/Onboarding/OnboardingMap/OnboardingMap_부산.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/Onboarding/OnboardingMap/OnboardingMap_서울.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/Onboarding/OnboardingMap/OnboardingMap_울산.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/Onboarding/OnboardingMap/OnboardingMap_인천.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/Onboarding/OnboardingMap/OnboardingMap_전라남도.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/Onboarding/OnboardingMap/OnboardingMap_전라북도.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/Onboarding/OnboardingMap/OnboardingMap_제주도.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/Onboarding/OnboardingMap/OnboardingMap_충청남도.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/Onboarding/OnboardingMap/OnboardingMap_충청북도.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/Onboarding/OnboardingMap/Onboarding_Blue.json
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/Onboarding/OnboardingMap/Onboarding_Green.json
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/Onboarding/OnboardingMap/Onboarding_Orange.json
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/Onboarding/OnboardingMap/Onboarding_Pink.json
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/Onboarding/OnboardingMap/Onboarding_Purple.json
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/Onboarding/OnboardingMap/Onboarding_Yellow.json
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/Onboarding/Reactor/OnboardingReactor.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/Onboarding/View/OnboardingView.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/Onboarding/ViewController/OnboardingViewController.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/RecordList/Reactor/RecordListReactor.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/RecordList/View/EmptyRecordView.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/RecordList/View/MenuAlertView.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/RecordList/View/RecordListCell.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/RecordList/View/RecordListHeaderView.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/RecordList/ViewController/RecordListViewController.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/Splash/ViewController/SplashViewController.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/dnd-11th-4-iOS.entitlements
Labels: 우연 🐶, FEAT

#22 [Setting] #22 - Network Layer 세팅
  dnd-11th-4-iOS/dnd-11th-4-iOS.xcodeproj/project.pbxproj
  dnd-11th-4-iOS/dnd-11th-4-iOS/Application/SceneDelegate.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Network/Base/BaseEndpoint.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Network/Base/BaseRequest.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Network/Base/HTTPHeaderField.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Network/Base/MDError.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Network/Base/NetworkManager.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Network/Base/Niltype.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Network/EndPoint/HomeEndPoint.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Network/Model/HomeResponse.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Network/Service/HomeService.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/Home/Model/OpacityColorType.swift
Labels: 우연 🐶, 찬미 🐹, SETTING

#23 [Feat] #15 - 기록하기 UI 및 바인딩 구현
  dnd-11th-4-iOS/Podfile
  dnd-11th-4-iOS/Podfile.lock
  dnd-11th-4-iOS/Pods/Manifest.lock
  dnd-11th-4-iOS/Pods/Pods.xcodeproj/project.pbxproj
  dnd-11th-4-iOS/Pods/RxKeyboard/LICENSE
  dnd-11th-4-iOS/Pods/RxKeyboard/README.md
  dnd-11th-4-iOS/Pods/RxKeyboard/Sources/RxKeyboard/RxKeyboard.swift
  dnd-11th-4-iOS/Pods/Target Support Files/Pods-dnd-11th-4-iOS/Pods-dnd-11th-4-iOS-acknowledgements.markdown
  dnd-11th-4-iOS/Pods/Target Support Files/Pods-dnd-11th-4-iOS/Pods-dnd-11th-4-iOS-acknowledgements.plist
  dnd-11th-4-iOS/Pods/Target Support Files/Pods-dnd-11th-4-iOS/Pods-dnd-11th-4-iOS-frameworks-Debug-input-files.xcfilelist
  dnd-11th-4-iOS/Pods/Target Support Files/Pods-dnd-11th-4-iOS/Pods-dnd-11th-4-iOS-frameworks-Debug-output-files.xcfilelist
  dnd-11th-4-iOS/Pods/Target Support Files/Pods-dnd-11th-4-iOS/Pods-dnd-11th-4-iOS-frameworks-Release-input-files.xcfilelist
  dnd-11th-4-iOS/Pods/Target Support Files/Pods-dnd-11th-4-iOS/Pods-dnd-11th-4-iOS-frameworks-Release-output-files.xcfilelist
  dnd-11th-4-iOS/Pods/Target Support Files/Pods-dnd-11th-4-iOS/Pods-dnd-11th-4-iOS-frameworks.sh
  dnd-11th-4-iOS/Pods/Target Support Files/Pods-dnd-11th-4-iOS/Pods-dnd-11th-4-iOS.debug.xcconfig
  dnd-11th-4-iOS/Pods/Target Support Files/Pods-dnd-11th-4-iOS/Pods-dnd-11th-4-iOS.release.xcconfig
  dnd-11th-4-iOS/Pods/Target Support Files/RxKeyboard/RxKeyboard-Info.plist
  dnd-11th-4-iOS/Pods/Target Support Files/RxKeyboard/RxKeyboard-dummy.m
  dnd-11th-4-iOS/Pods/Target Support Files/RxKeyboard/RxKeyboard-prefix.pch
  dnd-11th-4-iOS/Pods/Target Support Files/RxKeyboard/RxKeyboard-umbrella.h
  dnd-11th-4-iOS/Pods/Target Support Files/RxKeyboard/RxKeyboard.debug.xcconfig
  dnd-11th-4-iOS/Pods/Target Support Files/RxKeyboard/RxKeyboard.modulemap
  dnd-11th-4-iOS/Pods/Target Support Files/RxKeyboard/RxKeyboard.release.xcconfig
  dnd-11th-4-iOS/dnd-11th-4-iOS.xcodeproj/project.pbxproj
  dnd-11th-4-iOS/dnd-11th-4-iOS/Application/Info.plist
  dnd-11th-4-iOS/dnd-11th-4-iOS/Application/SceneDelegate.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/DesignSystem/Font/Font.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/Extension/CATransition+.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/UIComponent/MDNavigationBar.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/UIComponent/MDTextField.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/UIComponent/MDToast.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Global/UIComponent/MDToastView.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/Home/Reactor/HomeMapReactor.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/Home/ViewController/HomeMapViewController.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/PopUp/PopupViewController.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/PopUp/RecordCancelPopUpViewController.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/Record/Cell/RecordImageCell.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/Record/Empty.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/Record/Reactor/RecordReactor.swift
  dnd-11th-4-iOS/dnd-11th-4-iOS/Presentation/Record/ViewController/RecordViewController.swift
Labels: 찬미 🐹, FEAT
